DROP TABLE IF EXISTS beers, cars;

CREATE TABLE beers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  abv TEXT NOT NULL,
  color TEXT
);

CREATE TABLE cars (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price INT NOT NULL,
  color TEXT
)